### ISSUE TITLE
Error in predict.py script

### ISSUE THREAD

**Issue by jivankandel** [stemylonas/DeepSurf#4]
1570 atoms
9981 points     (3420 contact, 6561 reentrant)
8636.33 sq. A   (3006.94 contact, 5629.39 reentrant)
1.16 pts/sq.A   (1.14 contact, 1.17 reentrant)
Traceback (most recent call last):
  File "predict.py", line 42, in <module>
    prot = Protein(args.prot_file,args.protonate,args.expand,args.f,args.output, args.discard_points)
  File "/home/jeevan/DeepSurf/protein.py", line 25, in __init__
    self.surf_points, self.surf_normals = simplify_dms(surfpoints_file,f)
  File "/home/jeevan/DeepSurf/lib.py", line 73, in simplify_dms
    kmeans = KMeans(n_clusters=nCl,max_iter=300,n_init=1).fit(coords)
  File "/home/jeevan/anaconda3/envs/deepsurf/lib/python3.5/site-packages/sklearn/cluster/k_means_.py", line 896, in fit
    return_n_iter=True)
  File "/home/jeevan/anaconda3/envs/deepsurf/lib/python3.5/site-packages/sklearn/cluster/k_means_.py", line 346, in k_means
    x_squared_norms=x_squared_norms, random_state=random_state)
  File "/home/jeevan/anaconda3/envs/deepsurf/lib/python3.5/site-packages/sklearn/cluster/k_means_.py", line 395, in _kmeans_single_elkan
    x_squared_norms=x_squared_norms)
  File "/home/jeevan/anaconda3/envs/deepsurf/lib/python3.5/site-packages/sklearn/cluster/k_means_.py", line 684, in _init_centroids
    x_squared_norms=x_squared_norms)
  File "/home/jeevan/anaconda3/envs/deepsurf/lib/python3.5/site-packages/sklearn/cluster/k_means_.py", line 79, in _k_init
    centers = np.empty((n_clusters, n_features), dtype=X.dtype)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by SJTUMisaka** [comment]
Same error.
Just change line 71 in lib.py:  / -> //
will fix it.

**Comment by stemylonas** [comment]
Thanks for the observation.
The issue has been fixed.
